name: Format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer

      - uses: pnpm/action-setup@v4
        with:
          cache: true

      - run: composer install --no-interaction --prefer-dist

      - run: pnpm install --frozen-lockfile

      - run: composer fix

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Format code
          branch: ${{ github.head_ref }}
